//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2026 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// Generated by the GenerateStaticHeaderTable target. Do not edit.
// Regenerate with: swift run GenerateStaticHeaderTable Sources/QPACK/Headers

import HTTPTypes

/// All the static header table entries as defined in RFC 9204 § 3.1.
///
/// The absolute index is the position, which is the array index. Note that the QPACK
/// static table is indexed from 0, whereas the HPACK static table is indexed from 1.
let staticHeaderTable: [(HTTPField.Name, String)] = [
    (.init(parsed: ":authority")!, ""),  // 0
    (.init(parsed: ":path")!, "/"),  // 1
    (.init(parsed: "age")!, "0"),  // 2
    (.init(parsed: "content-disposition")!, ""),  // 3
    (.init(parsed: "content-length")!, "0"),  // 4
    (.init(parsed: "cookie")!, ""),  // 5
    (.init(parsed: "date")!, ""),  // 6
    (.init(parsed: "etag")!, ""),  // 7
    (.init(parsed: "if-modified-since")!, ""),  // 8
    (.init(parsed: "if-none-match")!, ""),  // 9
    (.init(parsed: "last-modified")!, ""),  // 10
    (.init(parsed: "link")!, ""),  // 11
    (.init(parsed: "location")!, ""),  // 12
    (.init(parsed: "referer")!, ""),  // 13
    (.init(parsed: "set-cookie")!, ""),  // 14
    (.init(parsed: ":method")!, "CONNECT"),  // 15
    (.init(parsed: ":method")!, "DELETE"),  // 16
    (.init(parsed: ":method")!, "GET"),  // 17
    (.init(parsed: ":method")!, "HEAD"),  // 18
    (.init(parsed: ":method")!, "OPTIONS"),  // 19
    (.init(parsed: ":method")!, "POST"),  // 20
    (.init(parsed: ":method")!, "PUT"),  // 21
    (.init(parsed: ":scheme")!, "http"),  // 22
    (.init(parsed: ":scheme")!, "https"),  // 23
    (.init(parsed: ":status")!, "103"),  // 24
    (.init(parsed: ":status")!, "200"),  // 25
    (.init(parsed: ":status")!, "304"),  // 26
    (.init(parsed: ":status")!, "404"),  // 27
    (.init(parsed: ":status")!, "503"),  // 28
    (.init(parsed: "accept")!, "*/*"),  // 29
    (.init(parsed: "accept")!, "application/dns-message"),  // 30
    (.init(parsed: "accept-encoding")!, "gzip, deflate, br"),  // 31
    (.init(parsed: "accept-ranges")!, "bytes"),  // 32
    (.init(parsed: "access-control-allow-headers")!, "cache-control"),  // 33
    (.init(parsed: "access-control-allow-headers")!, "content-type"),  // 34
    (.init(parsed: "access-control-allow-origin")!, "*"),  // 35
    (.init(parsed: "cache-control")!, "max-age=0"),  // 36
    (.init(parsed: "cache-control")!, "max-age=2592000"),  // 37
    (.init(parsed: "cache-control")!, "max-age=604800"),  // 38
    (.init(parsed: "cache-control")!, "no-cache"),  // 39
    (.init(parsed: "cache-control")!, "no-store"),  // 40
    (.init(parsed: "cache-control")!, "public, max-age=31536000"),  // 41
    (.init(parsed: "content-encoding")!, "br"),  // 42
    (.init(parsed: "content-encoding")!, "gzip"),  // 43
    (.init(parsed: "content-type")!, "application/dns-message"),  // 44
    (.init(parsed: "content-type")!, "application/javascript"),  // 45
    (.init(parsed: "content-type")!, "application/json"),  // 46
    (.init(parsed: "content-type")!, "application/x-www-form-urlencoded"),  // 47
    (.init(parsed: "content-type")!, "image/gif"),  // 48
    (.init(parsed: "content-type")!, "image/jpeg"),  // 49
    (.init(parsed: "content-type")!, "image/png"),  // 50
    (.init(parsed: "content-type")!, "text/css"),  // 51
    (.init(parsed: "content-type")!, "text/html; charset=utf-8"),  // 52
    (.init(parsed: "content-type")!, "text/plain"),  // 53
    (.init(parsed: "content-type")!, "text/plain;charset=utf-8"),  // 54
    (.init(parsed: "range")!, "bytes=0-"),  // 55
    (.init(parsed: "strict-transport-security")!, "max-age=31536000"),  // 56
    (.init(parsed: "strict-transport-security")!, "max-age=31536000; includesubdomains"),  // 57
    (.init(parsed: "strict-transport-security")!, "max-age=31536000; includesubdomains; preload"),  // 58
    (.init(parsed: "vary")!, "accept-encoding"),  // 59
    (.init(parsed: "vary")!, "origin"),  // 60
    (.init(parsed: "x-content-type-options")!, "nosniff"),  // 61
    (.init(parsed: "x-xss-protection")!, "1; mode=block"),  // 62
    (.init(parsed: ":status")!, "100"),  // 63
    (.init(parsed: ":status")!, "204"),  // 64
    (.init(parsed: ":status")!, "206"),  // 65
    (.init(parsed: ":status")!, "302"),  // 66
    (.init(parsed: ":status")!, "400"),  // 67
    (.init(parsed: ":status")!, "403"),  // 68
    (.init(parsed: ":status")!, "421"),  // 69
    (.init(parsed: ":status")!, "425"),  // 70
    (.init(parsed: ":status")!, "500"),  // 71
    (.init(parsed: "accept-language")!, ""),  // 72
    (.init(parsed: "access-control-allow-credentials")!, "FALSE"),  // 73
    (.init(parsed: "access-control-allow-credentials")!, "TRUE"),  // 74
    (.init(parsed: "access-control-allow-headers")!, "*"),  // 75
    (.init(parsed: "access-control-allow-methods")!, "get"),  // 76
    (.init(parsed: "access-control-allow-methods")!, "get, post, options"),  // 77
    (.init(parsed: "access-control-allow-methods")!, "options"),  // 78
    (.init(parsed: "access-control-expose-headers")!, "content-length"),  // 79
    (.init(parsed: "access-control-request-headers")!, "content-type"),  // 80
    (.init(parsed: "access-control-request-method")!, "get"),  // 81
    (.init(parsed: "access-control-request-method")!, "post"),  // 82
    (.init(parsed: "alt-svc")!, "clear"),  // 83
    (.init(parsed: "authorization")!, ""),  // 84
    (.init(parsed: "content-security-policy")!, "script-src 'none'; object-src 'none'; base-uri 'none'"),  // 85
    (.init(parsed: "early-data")!, "1"),  // 86
    (.init(parsed: "expect-ct")!, ""),  // 87
    (.init(parsed: "forwarded")!, ""),  // 88
    (.init(parsed: "if-range")!, ""),  // 89
    (.init(parsed: "origin")!, ""),  // 90
    (.init(parsed: "purpose")!, "prefetch"),  // 91
    (.init(parsed: "server")!, ""),  // 92
    (.init(parsed: "timing-allow-origin")!, "*"),  // 93
    (.init(parsed: "upgrade-insecure-requests")!, "1"),  // 94
    (.init(parsed: "user-agent")!, ""),  // 95
    (.init(parsed: "x-forwarded-for")!, ""),  // 96
    (.init(parsed: "x-frame-options")!, "deny"),  // 97
    (.init(parsed: "x-frame-options")!, "sameorigin"),  // 98
]

extension StaticHeaderTable {
    /// Resolves `canonicalName` to the static table indices carrying that name, or an empty
    /// group if the static table doesn't carry it.
    ///
    /// A trie over the UTF-8 bytes of the canonical (lowercase) name: it dispatches on the
    /// length first, then on whichever byte positions discriminate the remaining candidates,
    /// and finally confirms with a single whole-string comparison. Each dispatch is a jump
    /// table, so a lookup costs a handful of loads instead of hashing the whole name.
    ///
    /// `utf8` must be `canonicalName`'s UTF-8 bytes; call `entryGroup(for:)` instead.
    static func entryGroup(canonicalName: String, utf8: UnsafeBufferPointer<UInt8>) -> StaticEntryGroup {
        switch utf8.count {
        case 3:
            canonicalName == "age" ? StaticEntryGroup(2, 3) : .none
        case 4:
            switch utf8[position: 0] {
            case UInt8(ascii: "d"):
                canonicalName == "date" ? StaticEntryGroup(6, 7) : .none
            case UInt8(ascii: "e"):
                canonicalName == "etag" ? StaticEntryGroup(7, 8) : .none
            case UInt8(ascii: "l"):
                canonicalName == "link" ? StaticEntryGroup(11, 12) : .none
            case UInt8(ascii: "v"):
                canonicalName == "vary" ? StaticEntryGroup(59, 61) : .none
            default:
                .none
            }
        case 5:
            switch utf8[position: 0] {
            case UInt8(ascii: ":"):
                canonicalName == ":path" ? StaticEntryGroup(1, 2) : .none
            case UInt8(ascii: "r"):
                canonicalName == "range" ? StaticEntryGroup(55, 56) : .none
            default:
                .none
            }
        case 6:
            switch utf8[position: 0] {
            case UInt8(ascii: "a"):
                canonicalName == "accept" ? StaticEntryGroup(29, 31) : .none
            case UInt8(ascii: "c"):
                canonicalName == "cookie" ? StaticEntryGroup(5, 6) : .none
            case UInt8(ascii: "o"):
                canonicalName == "origin" ? StaticEntryGroup(90, 91) : .none
            case UInt8(ascii: "s"):
                canonicalName == "server" ? StaticEntryGroup(92, 93) : .none
            default:
                .none
            }
        case 7:
            switch utf8[position: 3] {
            case UInt8(ascii: "-"):
                canonicalName == "alt-svc" ? StaticEntryGroup(83, 84) : .none
            case UInt8(ascii: "a"):
                canonicalName == ":status" ? StaticEntryGroup(24, 29, 63, 72) : .none
            case UInt8(ascii: "e"):
                canonicalName == "referer" ? StaticEntryGroup(13, 14) : .none
            case UInt8(ascii: "h"):
                canonicalName == ":scheme" ? StaticEntryGroup(22, 24) : .none
            case UInt8(ascii: "p"):
                canonicalName == "purpose" ? StaticEntryGroup(91, 92) : .none
            case UInt8(ascii: "t"):
                canonicalName == ":method" ? StaticEntryGroup(15, 22) : .none
            default:
                .none
            }
        case 8:
            switch utf8[position: 0] {
            case UInt8(ascii: "i"):
                canonicalName == "if-range" ? StaticEntryGroup(89, 90) : .none
            case UInt8(ascii: "l"):
                canonicalName == "location" ? StaticEntryGroup(12, 13) : .none
            default:
                .none
            }
        case 9:
            switch utf8[position: 0] {
            case UInt8(ascii: "e"):
                canonicalName == "expect-ct" ? StaticEntryGroup(87, 88) : .none
            case UInt8(ascii: "f"):
                canonicalName == "forwarded" ? StaticEntryGroup(88, 89) : .none
            default:
                .none
            }
        case 10:
            switch utf8[position: 0] {
            case UInt8(ascii: ":"):
                canonicalName == ":authority" ? StaticEntryGroup(0, 1) : .none
            case UInt8(ascii: "e"):
                canonicalName == "early-data" ? StaticEntryGroup(86, 87) : .none
            case UInt8(ascii: "s"):
                canonicalName == "set-cookie" ? StaticEntryGroup(14, 15) : .none
            case UInt8(ascii: "u"):
                canonicalName == "user-agent" ? StaticEntryGroup(95, 96) : .none
            default:
                .none
            }
        case 12:
            canonicalName == "content-type" ? StaticEntryGroup(44, 55) : .none
        case 13:
            switch utf8[position: 5] {
            case UInt8(ascii: "-"):
                canonicalName == "cache-control" ? StaticEntryGroup(36, 42) : .none
            case UInt8(ascii: "m"):
                canonicalName == "last-modified" ? StaticEntryGroup(10, 11) : .none
            case UInt8(ascii: "n"):
                canonicalName == "if-none-match" ? StaticEntryGroup(9, 10) : .none
            case UInt8(ascii: "r"):
                canonicalName == "authorization" ? StaticEntryGroup(84, 85) : .none
            case UInt8(ascii: "t"):
                canonicalName == "accept-ranges" ? StaticEntryGroup(32, 33) : .none
            default:
                .none
            }
        case 14:
            canonicalName == "content-length" ? StaticEntryGroup(4, 5) : .none
        case 15:
            switch utf8[position: 7] {
            case UInt8(ascii: "-"):
                canonicalName == "x-frame-options" ? StaticEntryGroup(97, 99) : .none
            case UInt8(ascii: "e"):
                canonicalName == "accept-encoding" ? StaticEntryGroup(31, 32) : .none
            case UInt8(ascii: "l"):
                canonicalName == "accept-language" ? StaticEntryGroup(72, 73) : .none
            case UInt8(ascii: "r"):
                canonicalName == "x-forwarded-for" ? StaticEntryGroup(96, 97) : .none
            default:
                .none
            }
        case 16:
            switch utf8[position: 0] {
            case UInt8(ascii: "c"):
                canonicalName == "content-encoding" ? StaticEntryGroup(42, 44) : .none
            case UInt8(ascii: "x"):
                canonicalName == "x-xss-protection" ? StaticEntryGroup(62, 63) : .none
            default:
                .none
            }
        case 17:
            canonicalName == "if-modified-since" ? StaticEntryGroup(8, 9) : .none
        case 19:
            switch utf8[position: 0] {
            case UInt8(ascii: "c"):
                canonicalName == "content-disposition" ? StaticEntryGroup(3, 4) : .none
            case UInt8(ascii: "t"):
                canonicalName == "timing-allow-origin" ? StaticEntryGroup(93, 94) : .none
            default:
                .none
            }
        case 22:
            canonicalName == "x-content-type-options" ? StaticEntryGroup(61, 62) : .none
        case 23:
            canonicalName == "content-security-policy" ? StaticEntryGroup(85, 86) : .none
        case 25:
            switch utf8[position: 0] {
            case UInt8(ascii: "s"):
                canonicalName == "strict-transport-security" ? StaticEntryGroup(56, 59) : .none
            case UInt8(ascii: "u"):
                canonicalName == "upgrade-insecure-requests" ? StaticEntryGroup(94, 95) : .none
            default:
                .none
            }
        case 27:
            canonicalName == "access-control-allow-origin" ? StaticEntryGroup(35, 36) : .none
        case 28:
            switch utf8[position: 21] {
            case UInt8(ascii: "h"):
                canonicalName == "access-control-allow-headers" ? StaticEntryGroup(33, 35, 75, 76) : .none
            case UInt8(ascii: "m"):
                canonicalName == "access-control-allow-methods" ? StaticEntryGroup(76, 79) : .none
            default:
                .none
            }
        case 29:
            switch utf8[position: 15] {
            case UInt8(ascii: "e"):
                canonicalName == "access-control-expose-headers" ? StaticEntryGroup(79, 80) : .none
            case UInt8(ascii: "r"):
                canonicalName == "access-control-request-method" ? StaticEntryGroup(81, 83) : .none
            default:
                .none
            }
        case 30:
            canonicalName == "access-control-request-headers" ? StaticEntryGroup(80, 81) : .none
        case 32:
            canonicalName == "access-control-allow-credentials" ? StaticEntryGroup(73, 75) : .none
        default:
            .none
        }
    }
}
