//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2026 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

/// Accumulates generated Swift source, tracking indentation.
struct SourceWriter {
    private var lines: [String] = []
    private var indentation = 0

    var contents: String {
        self.lines.joined(separator: "\n") + "\n"
    }

    mutating func write(_ line: String = "") {
        if line.isEmpty {
            self.lines.append("")
        } else {
            self.lines.append(String(repeating: " ", count: self.indentation) + line)
        }
    }

    mutating func write(lines: [String]) {
        for line in lines {
            self.write(line)
        }
    }

    /// Writes `header`, then `body` indented one level, then `terminator`.
    mutating func writeBlock(_ header: String, terminator: String = "}", _ body: (inout Self) -> Void) {
        self.write(header)
        self.indentation += 4
        body(&self)
        self.indentation -= 4
        self.write(terminator)
    }

    /// Writes a `switch` statement. `body` writes the cases via ``writeCase``.
    ///
    /// `.swift-format` sets `indentSwitchCaseLabels: false`, so case labels sit at the same
    /// indentation as the `switch` itself and only their bodies are indented.
    mutating func writeSwitch(_ subject: String, _ body: (inout Self) -> Void) {
        self.write("switch \(subject) {")
        body(&self)
        self.write("}")
    }

    /// Writes one case of a ``writeSwitch``: the label at the current indentation, `body` one
    /// level in.
    mutating func writeCase(_ label: String, _ body: (inout Self) -> Void) {
        self.write("\(label):")
        self.indentation += 4
        body(&self)
        self.indentation -= 4
    }

    mutating func writeLicenseHeader() {
        self.write(
            lines: [
                "//===----------------------------------------------------------------------===//",
                "//",
                "// This source file is part of the SwiftNIO open source project",
                "//",
                "// Copyright (c) 2026 Apple Inc. and the SwiftNIO project authors",
                "// Licensed under Apache License v2.0",
                "//",
                "// See LICENSE.txt for license information",
                "// See CONTRIBUTORS.txt for the list of SwiftNIO project authors",
                "//",
                "// SPDX-License-Identifier: Apache-2.0",
                "//",
                "//===----------------------------------------------------------------------===//",
            ]
        )
        self.write()
        self.write("// Generated by the GenerateStaticHeaderTable target. Do not edit.")
        self.write("// Regenerate with: swift run GenerateStaticHeaderTable Sources/QPACK/Headers")
        self.write()
    }
}

extension String {
    /// This string as a Swift string literal.
    var swiftLiteral: String {
        var escaped = ""
        for character in self {
            switch character {
            case "\\": escaped += "\\\\"
            case "\"": escaped += "\\\""
            default: escaped.append(character)
            }
        }
        return "\"\(escaped)\""
    }
}

extension UInt8 {
    /// This byte as `UInt8(ascii: "x")`, which reads better than a bare number in a `switch`.
    var asciiLiteral: String {
        "UInt8(ascii: \(String(UnicodeScalar(self)).swiftLiteral))"
    }
}
